using DevExpress.XtraEditors;
using QuanLyXiNghiepMay.R;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.ClipboardSource.SpreadsheetML;
using DevExpress.XtraGrid.Views.Base;
using System.Data.Entity.SqlServer;

namespace QuanLyXiNghiepMay.Forms.Form_Tables.Form_Parent
{
    public partial class XtraFormSanPham : DevExpress.XtraBars.Ribbon.RibbonForm
    {


        public XtraFormSanPham()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities dbContext = new QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.SanPhams.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.SanPhams.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }


        private void XtraFormSanPham_Load(object sender, EventArgs e)
        {
            clearForm();
            ribbonControl1.SelectPage(ribbonPage1);
        }





        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Precenter.reloadDataSource(this, gridControl1);
        }

        private void clearForm()
        {
            String ma = Precenter.getMaSanPham();
            textEditMaSanPham.Text = ma;
            textEditTenSanPham.Focus();
            textEditTenSanPham.Text = "";
            textEditGhiChu.Text = "";
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            int rowHandle = e.RowHandle;
            SanPham sanPham = (SanPham)gridView1.GetRow(e.RowHandle);


            textEditMaSanPham.Text = sanPham.ma;
            textEditTenSanPham.Text = sanPham.ten;
            textEditGhiChu.Text = sanPham.ghiChu;
        }


        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (!Controler.isTextInputValid(textEditTenSanPham.Text))
            {
                Controler.messageBoxShow(MyTemplateString.MESSAGE_INPUT_ERROR, MyTemplateString.TITLE_WARNING);
            }
            else
            {
                try
                {
                    addSanPham();
                    Precenter.reloadDataSource(this, gridControl1);
                    clearForm();
                }
                catch (Exception)
                {
                    Controler.messageBoxShow(MyTemplateString.MESSAGE_INSERT_ERROR, MyTemplateString.TITLE_WARNING);
                    textEditTenSanPham.Focus();
                }
            }
        }
        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (!Controler.isTextInputValid(textEditTenSanPham.Text))
            {
                Controler.messageBoxShow(MyTemplateString.MESSAGE_INPUT_ERROR, MyTemplateString.TITLE_WARNING);
            }
            else
            {
                try
                {
                    updateSanPham();
                    Precenter.reloadDataSource(this, gridControl1);
                    clearForm();
                }
                catch (Exception)
                {
                    Controler.messageBoxShow(MyTemplateString.MESSAGE_UPDATE_ERROR, MyTemplateString.TITLE_WARNING);
                    textEditTenSanPham.Focus();
                }
            }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Controler.isMessageBox(MyTemplateString.MESSAGE_DELETE, MyTemplateString.TITLE_WARNING))
            {
                try
                {
                    removeSanPham();
                    Precenter.reloadDataSource(this, gridControl1);
                    clearForm();
                }
                catch (Exception)
                {
                    if (textEditMaSanPham.Text == Precenter.getMaSanPham())
                    {
                        Controler.messageBoxShow(MyTemplateString.PICK_ONE_ROW, MyTemplateString.TITLE_WARNING);
                    }
                    else
                    {
                        Controler.messageBoxShow(MyTemplateString.MESSAGE_DELETE_ERROR, MyTemplateString.TITLE_WARNING);
                    }
                }
            }
        }

        private void updateSanPham()
        {
            SanPham sanPham = (from t in Precenter.data.SanPhams
                               where t.ma == textEditMaSanPham.Text
                               select t).SingleOrDefault();

            sanPham.ten = textEditTenSanPham.Text.Trim();
            sanPham.ghiChu = textEditGhiChu.Text.Trim();
            Precenter.data.SaveChanges();
        }
        private void addSanPham()
        {
            SanPham sanPham = new SanPham();
            sanPham.ma = textEditMaSanPham.Text.Trim();
            sanPham.ten = textEditTenSanPham.Text.Trim();
            sanPham.ghiChu = textEditGhiChu.Text.Trim();
            Precenter.data.SanPhams.Add(sanPham);
            Precenter.data.SaveChanges();
        }

        private void removeSanPham()
        {
            var sanPham = (
                            from sp in Precenter.data.SanPhams.ToList()
                            where sp.ma == textEditMaSanPham.Text
                            select sp
                                  ).SingleOrDefault();

            Precenter.data.SanPhams.Remove(sanPham);
            Precenter.data.SaveChanges();
        }





        private void barButtonItem5_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            clearForm();
        }

        private void barButtonItem6_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            clearForm();
        }

        private void barButtonItem7_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Dispose();
        }

        private void barButtonItem8_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            // Check whether the Grid Control can be previewed.
            if (!gridView1.GridControl.IsPrintingAvailable)
            {
                MessageBox.Show("The 'DevExpress.XtraPrinting' Library is not found", "Error");
                return;
            }
            else
            {
                if (barCheckItemHighlightEvenRow.Checked)
                {
                    gridView1.OptionsPrint.UsePrintStyles = true;
                    // Enable the AppearancePrint.EvenRow property's settings.
                    gridView1.OptionsPrint.EnableAppearanceEvenRow = true;
                    // Set the background color of the even rows.
                    gridView1.AppearancePrint.EvenRow.BackColor = Color.LightYellow;
                }
                else
                {
                    gridView1.OptionsPrint.UsePrintStyles = false;
                }
                // Opens the Preview window.
                if (barCheckItemWindown.Checked)
                {
                    gridView1.ShowRibbonPrintPreview();
                }
                else
                {
                    gridView1.ShowPrintPreview();
                }

            }
        }
    }
}