using DevExpress.XtraEditors;
using QuanLyXiNghiepMay.R;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.ClipboardSource.SpreadsheetML;
using DevExpress.XtraGrid.Views.Base;
using System.Data.Entity.SqlServer;

namespace QuanLyXiNghiepMay.Forms.Form_Tables.Form_Parent
{
    public partial class XtraFormSanPham : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities data = new QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities();

        public XtraFormSanPham()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities dbContext = new QuanLyXiNghiepMay.QuanLyVatTuCuaXiNghiepMayEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.SanPhams.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.SanPhams.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }


        private void XtraFormSanPham_Load(object sender, EventArgs e)
        {
            clearForm();
            ribbonControl1.SelectPage(ribbonPage1);
        }

        private void clearForm()
        {
            String ma = Precenter.getMaSanPham();
            textEditMaSanPham.Text = ma;
            textEditTenSanPham.Focus();
            textEditTenSanPham.Text = "";
            textEditGhiChu.Text = "";
        }

        private void reloadDataSource()
        {
            gridControl1.DataSource = data.SanPhams.ToList();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (!Controler.isTextInputValid(textEditTenSanPham.Text))
            {
                Controler.messageBoxShow(TemplateString.MESSAGE_INPUT_ERROR, TemplateString.TITLE_WARNING);
            }
            else
            {
                try
                {
                    addSanPham();
                    reloadDataSource();
                    clearForm();
                }
                catch (Exception)
                {
                    Controler.messageBoxShow(TemplateString.MESSAGE_INSERT_ERROR, TemplateString.TITLE_WARNING);
                    textEditTenSanPham.Focus();
                }
            }
        }

        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            clearForm();
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            int rowHandle = e.RowHandle;
            SanPham sanPham = (SanPham)gridView1.GetRow(e.RowHandle);


            textEditMaSanPham.Text = sanPham.ma;
            textEditTenSanPham.Text = sanPham.ten;
            textEditGhiChu.Text = sanPham.ghiChu;
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (!Controler.isTextInputValid(textEditTenSanPham.Text))
            {
                Controler.messageBoxShow(TemplateString.MESSAGE_INPUT_ERROR, TemplateString.TITLE_WARNING);
            }
            else
            {
                try
                {
                    updateSanPham();
                    reloadDataSource();
                    clearForm();
                }
                catch (Exception)
                {
                    Controler.messageBoxShow(TemplateString.MESSAGE_UPDATE_ERROR, TemplateString.TITLE_WARNING);
                    textEditTenSanPham.Focus();
                }
            }
        }

        private void updateSanPham()
        {
            SanPham sanPham = (from t in data.SanPhams
                               where t.ma == textEditMaSanPham.Text
                               select t).SingleOrDefault();

            sanPham.ten = textEditTenSanPham.Text.Trim();
            sanPham.ghiChu = textEditGhiChu.Text.Trim();
            data.SaveChanges();
        }
        private void addSanPham()
        {
            SanPham sanPham = new SanPham();
            sanPham.ma = textEditMaSanPham.Text.Trim();
            sanPham.ten = textEditTenSanPham.Text.Trim();
            sanPham.ghiChu = textEditGhiChu.Text.Trim();
            data.SanPhams.Add(sanPham);
            data.SaveChanges();
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (Controler.isMessageBox(TemplateString.MESSAGE_DELETE, TemplateString.TITLE_WARNING))
            {
                try
                {
                    var sanPham = (
                            from sp in data.SanPhams.ToList()
                            where sp.ma == textEditMaSanPham.Text
                            select sp
                                  ).SingleOrDefault();

                    data.SanPhams.Remove(sanPham);
                    data.SaveChanges();
                    reloadDataSource();
                    clearForm();
                }
                catch (Exception)
                {
                    if (textEditMaSanPham.Text == Precenter.getMaSanPham())
                    {
                        Controler.messageBoxShow(TemplateString.PICK_ONE_ROW, TemplateString.TITLE_WARNING);
                    }
                    else
                    {
                        Controler.messageBoxShow(TemplateString.MESSAGE_DELETE_ERROR, TemplateString.TITLE_WARNING);
                    }
                }
            }
        }

        private void barButtonItem5_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void barButtonItem6_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            clearForm();
        }

        private void barButtonItem7_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Dispose();
        }
    }
}