//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXiNghiepMay
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhMuc
    {
        public string maNguyenLieu { get; set; }
        public string maSanPham { get; set; }
        public string donViTinh { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
